spring:                                                                                                                                                                                                                                                                                                                     
  application:
    name: gateway-service
server:
  port: 9000
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
zuul:
  prefix: /                                                                                                                                       
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:9001
    ambacam-service:
      path: /ambacam/**
      url: http://localhost:9002